name: npmjs.com

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check
      - uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: 'latest'
      - name: Build wasm
        working-directory: ./bindings/wasm
        run: wasm-pack build

      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'

      - working-directory: ./bindings/wasm/js
        run: yarn install
      - working-directory: ./bindings/wasm/js
        run: yarn test

      - working-directory: ./bindings/wasm/pkg
        run: yarn install
      - working-directory: ./bindings/wasm/pkg
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
