name: WASM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: 'latest'
      - name: Build wasm
        working-directory: ./bindings/wasm
        run: wasm-pack build
      - working-directory: ./bindings/wasm/js
        run: yarn install
      - working-directory: ./bindings/wasm/js
        run: yarn test
